### ISSUE TITLE
Dispatching a "submit" event without detail: {} raises an error.

### ISSUE THREAD

**Issue by brodyhoskins** [ParamagicDev/mrujs#171]
#### Expected Behaviour

An `<a>` tag that submits a form using JavaScript `dispatchEvent` shouldn't by handled by mrujs.

#### Actual Behaviour

The form is never submitted due to an error:

`TypeError: null is not an object (evaluating 'event.detail.submitter') (mrujs.module:373)`

#### Steps to Reproduce

Create a link with the following HTML:

```html
<a href="/somewhere" data-action="form#sync" data-form-target="syncButton">Some Link</a>
```

Handle it with Stimulus:

```javascript
    sync(e) {
        e.preventDefault()

        this.syncButtonTarget.classList.add('disabled')
        this.formTarget.action = this.syncButtonTarget.href
        this.formTarget.querySelector('input[name="authenticity_token"]').value = document.querySelector('meta[name="csrf-token"]').content
        this.formTarget.dispatchEvent(new CustomEvent('submit', { bubbles: true, cancelable: true }))
    }
```

**Comment by ParamagicDev** [comment]
@brodyhoskins this is expected behavior that mrujs . However, it should just gracefully stop and carry on since the elemnt doesnt have `data-remote` on it. The real fix is for me to have this just return undefined when no detail is provided. https://github.com/ParamagicDev/mrujs/blob/ac8a2d4c4324ff571f9e7ae62295c4c9f4760f03/src/submitFinder.ts#L10

In addition, the remote check should be the first thing that happens here:

https://github.com/ParamagicDev/mrujs/blob/af7706af6f12ada76a4afae023fa8a11ab79a706/src/formSubmitDispatcher.ts#L35-L41

In the meantime, to get you a fix right now, this would fix it for you:

```js
this.formTarget.dispatchEvent(new CustomEvent('submit', { bubbles: true, cancelable: true, detail: {} }))
```

**Comment by brodyhoskins** [comment]
Hey @ParamagicDev, I do see that the workaround resolves our issue. Thank you so much!

**Comment by ParamagicDev** [comment]
@brodyhoskins no problem! I'll work on a proper fix so that this doesn't happen again.

**Comment by ParamagicDev** [comment]
https://github.com/ParamagicDev/mrujs/pull/172

This should fix it. `0.7.2` has the fix.
