### ISSUE TITLE
should `mrujs.fetch` trigger the event chain?

### ISSUE THREAD

**Issue by ParamagicDev** [ParamagicDev/mrujs#40]
#### Describe Problem

When calling `window.mrujs.fetch()` should it trigger the `ajax:<name>` events?

#### Additional Details

UJS did not do this, but I view Mrujs as a superset and wonder if some cool interactions could happen from this....

Edit:

thumbsup for "yes trigger events"

thumbsdown for "no, async / await is plenty."

**Comment by ParamagicDev** [comment]
And as a follow up, should you be able to opt-in / opt-out of dispatching events when calling fetch? 🤔

**Comment by existentialmutt** [comment]
Good catch!  Thinking about it this morning, my personal preference is to dispatch them with an available opt-out.  Here’s a bunch of reasons.

This is new functionality, so nobody’s going to have expectations based on old UJS behavior.  It’s also a nice to have.  As a user I can recreate this now if I need to by manually dispatching events from the promise handlers.

That said, I can see a use where I’m sharing common handling behavior between data-remote links/forms and fetch requests.  Having fetch dispatch events would be really convenient for that.  But honestly 90% of my fetches will just be handling the promise.

One other consideration is on the code itself.  Do data-remote links/forms go through mrujs.fetch under the hood?  If so that could be a case for always dispatching events to keep things consistent.

I guess events would fire on ‘document’ since there’s no associated DOM node?  Maybe callers could provide an eventTarget option that takes a DOM node and the events will be dispatched from there.  This would be useful for integrating with data-remote handling based on bubbling.

**Comment by ParamagicDev** [comment]
@existentialmutt I havent fully thought about the API, but i do agree providing an element to trigger off of and a boolean for dispatching events is a good idea.

And yes, data-remote and data-method both hook into fetch, although slightly differently as theres an actual formSubmitDispatcher that handles dispatching events.

Perhaps something like `fetchWithEvents()` or `fetchAndDispatchEvent()` may be more explicit than using kwargs...the API needs a little more thinking. But i do agree it would be cool to hook onto events.

**Comment by existentialmutt** [comment]
cool!  My vote is for keyword args to keep the overall surface area of the API smaller.

**Comment by ParamagicDev** [comment]
@existentialmutt im still kinda back and forth on this. Im not sure theres a good reason to trigger the event chain...but i could also be entirely wrong...Im still thinking about this one.
